name: "merge branches"
author: "WXZhao"
description: "merge over-branch and base-branch to build-branch, in the case of conflicts it should automatically resolve the conflict by choosing over-branch"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email:
    description: The committer's email address
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: The committer's name
    required: true
    default: ${{ github.actor }}
